critiquebrainz/frontend/profile/applications/forms.py
from flask_wtf import Form
from flask_babel import gettext
from wtforms import StringField, validators


class ApplicationForm(Form):
    name = StringField(gettext('Application name'), [
        validators.DataRequired(message=gettext("Application name field is empty.")),
        validators.Length(min=3, message=gettext("Application name needs to be at least 3 characters long.")),
        validators.Length(max=64, message=gettext("Application name needs to be at most 64 characters long."))])
    desc = StringField(gettext('Description'), [
        validators.DataRequired(message=gettext("Client description field is empty.")),
        validators.Length(min=3, message=gettext("Client description needs to be at least 3 characters long.")),
        validators.Length(max=512, message=gettext("Client description needs to be at most 512 characters long."))])
    website = StringField(gettext('Homepage'), [
        validators.DataRequired(message=gettext("Homepage field is empty.")),
        validators.URL(message=gettext("Homepage is not a valid URI."))])
    redirect_uri = StringField(gettext('Authorization callback URL'), [
        validators.DataRequired(message=gettext("Authorization callback URL field is empty.")),
        validators.URL(message=gettext("Authorization callback URL is invalid."))])

critiquebrainz/frontend/__init__.py
from flask import Flask
from flask_debugtoolbar import DebugToolbarExtension


def create_app(debug=None):
    app = Flask(__name__)

    # Configuration files
    import critiquebrainz.default_config
    app.config.from_object(critiquebrainz.default_config)
    app.config.from_pyfile('../config.py', silent=True)
    if debug is not None:
        app.debug = debug

    # Error handling
    import errors
    errors.init_error_handlers(app)

    # Logging
    from critiquebrainz import loggers
    loggers.init_loggers(app)

    if app.debug:
        # Debug toolbar
        DebugToolbarExtension(app)
        app.config['DEBUG_TB_TEMPLATE_EDITOR_ENABLED'] = True

    from flask_uuid import FlaskUUID
    FlaskUUID(app)

    from critiquebrainz.data import db
    db.init_app(app)

    # Memcached
    if 'MEMCACHED_SERVERS' in app.config:
        from critiquebrainz import cache
        cache.init(app.config['MEMCACHED_SERVERS'],
                   app.config['MEMCACHED_NAMESPACE'],
                   debug=1 if app.debug else 0)

    import babel
    babel.init_app(app)

    import login
    login.login_manager.init_app(app)
    from login.provider import MusicBrainzAuthentication
    login.mb_auth = MusicBrainzAuthentication(
        name='musicbrainz',
        client_id=app.config['MUSICBRAINZ_CLIENT_ID'],
        client_secret=app.config['MUSICBRAINZ_CLIENT_SECRET'],
        authorize_url="https://musicbrainz.org/oauth2/authorize",
        access_token_url="https://musicbrainz.org/oauth2/token",
        base_url="https://musicbrainz.org/")

    # APIs
    from apis import mbspotify
    mbspotify.init(app.config['MBSPOTIFY_BASE_URI'], app.config['MBSPOTIFY_ACCESS_KEY'])
    from apis import musicbrainz
    musicbrainz.init(app.config['MUSICBRAINZ_USERAGENT'], critiquebrainz.__version__,
                     hostname=app.config['MUSICBRAINZ_HOSTNAME'])

    # Template utilities
    app.jinja_env.add_extension('jinja2.ext.do')
    from critiquebrainz.utils import reformat_date, reformat_datetime, track_length
    app.jinja_env.filters['date'] = reformat_date
    app.jinja_env.filters['datetime'] = reformat_datetime
    app.jinja_env.filters['track_length'] = track_length
    app.jinja_env.filters['release_group_details'] = musicbrainz.get_release_group_by_id

    # Blueprints
    from views import frontend_bp
    from review.views import review_bp
    from search.views import search_bp
    from artist.views import artist_bp
    from release_group.views import release_group_bp
    from mapping.views import mapping_bp
    from user.views import user_bp
    from profile.views import profile_bp
    from profile.applications.views import profile_apps_bp
    from login.views import login_bp
    from oauth.views import oauth_bp
    from reports.views import reports_bp

    app.register_blueprint(frontend_bp)
    app.register_blueprint(review_bp, url_prefix='/review')
    app.register_blueprint(search_bp, url_prefix='/search')
    app.register_blueprint(artist_bp, url_prefix='/artist')
    app.register_blueprint(release_group_bp, url_prefix='/release-group')
    app.register_blueprint(mapping_bp, url_prefix='/mapping')
    app.register_blueprint(user_bp, url_prefix='/user')
    app.register_blueprint(profile_bp, url_prefix='/profile')
    app.register_blueprint(profile_apps_bp, url_prefix='/profile/applications')
    app.register_blueprint(login_bp, url_prefix='/login')
    app.register_blueprint(oauth_bp, url_prefix='/oauth')
    app.register_blueprint(reports_bp, url_prefix='/reports')

    return app

critiquebrainz/frontend/apis/__init__.py
"""
This package (api) provides modules to access external services:
 - MusicBrainz (with advanced relationship support)
 - Spotify
 - mbspotify

See documentation in each module for information about usage.
"""

critiquebrainz/frontend/artist/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_babel import gettext
from werkzeug.exceptions import BadRequest, NotFound
from critiquebrainz.frontend.apis import musicbrainz
from critiquebrainz.data.model.review import Review

artist_bp = Blueprint('artist', __name__)


@artist_bp.route('/<uuid:id>')
def entity(id):
    """Artist page.

    Displays release groups (split up into several sections depending on their
    type), artist information (type, members/member of, external links).
    """
    artist = musicbrainz.get_artist_by_id(id)
    if not artist:
        raise NotFound(gettext("Sorry, we couldn't find an artist with that MusicBrainz ID."))

    # Preparing artist-rels
    if 'band-members' in artist:
        artist['current_members'] = []
        artist['former_members'] = []
        for member in artist['band-members']:
            if 'ended' in member and member['ended'] == 'true':
                artist['former_members'].append(member)
            else:
                artist['current_members'].append(member)


    release_type = request.args.get('release_type', default='album')
    if release_type not in ['album', 'single', 'ep', 'broadcast', 'other']:  # supported release types
        raise BadRequest("Unsupported release type.")

    page = int(request.args.get('page', default=1))
    if page < 1:
        return redirect(url_for('.reviews'))
    limit = 20
    offset = (page - 1) * limit
    count, release_groups = musicbrainz.browse_release_groups(artist_id=id, release_types=[release_type],
                                                              limit=limit, offset=offset)
    for release_group in release_groups:
        # TODO(roman): Count reviews instead of fetching them.
        reviews, review_count = Review.list(release_group=release_group['id'], sort='created', limit=1)
        release_group['review_count'] = review_count
    return render_template('artist.html', id=id, artist=artist, release_type=release_type,
                           release_groups=release_groups, page=page, limit=limit, count=count)

critiquebrainz/frontend/login/__init__.py
"""
Package login provides authentication functionality for CritiqueBrainz.

It is based on OAuth2 protocol. MusicBrainz is the only supported provider.
"""
from flask import redirect, url_for
from flask_login import LoginManager, current_user
from flask_babel import gettext
from critiquebrainz.data.model.user import User
from werkzeug.exceptions import Unauthorized
from functools import wraps

mb_auth = None

login_manager = LoginManager()
login_manager.login_view = 'login.index'
login_manager.login_message = gettext(u"Please sign in to access this page.")
login_manager.localize_callback = gettext


@login_manager.user_loader
def load_user(user_id):
    return User.get(id=user_id)


def login_forbidden(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if current_user.is_anonymous() is False:
            return redirect(url_for('frontend.index'))
        return f(*args, **kwargs)

    return decorated


def admin_view(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not current_user.is_admin():
            raise Unauthorized(gettext('You must be an administrator to view this page.'))
        return f(*args, **kwargs)

    return decorated

critiquebrainz/frontend/login/views.py
from flask import Blueprint, request, redirect, render_template, url_for, session, flash
from flask_login import login_user, logout_user, login_required
from flask_babel import gettext
from critiquebrainz.frontend.login import mb_auth, login_forbidden

login_bp = Blueprint('login', __name__)


@login_bp.route('/')
@login_forbidden
def index():
    return render_template('login/login.html')


@login_bp.route('/musicbrainz')
@login_forbidden
def musicbrainz():
    session['next'] = request.args.get('next')
    return redirect(mb_auth.get_authentication_uri())


@login_bp.route('/musicbrainz/post')
@login_forbidden
def musicbrainz_post():
    """Callback endpoint."""
    if mb_auth.validate_post_login():
        login_user(mb_auth.get_user())
        next = session.get('next')
        if next:
            return redirect(next)
    else:
        flash(gettext("Login failed."), 'error')
    return redirect(url_for('frontend.index'))


@login_bp.route('/logout')
@login_required
def logout():
    logout_user()
    session.clear()
    return redirect(url_for('frontend.index'))

critiquebrainz/frontend/mapping/__init__.py
"""
Package mapping is basically an interface for mbspotify project.

It allows users to create mappings between release groups and albums on
Spotify. These mappings are then used to show embedded Spotify player on some
pages. See https://github.com/metabrainz/mbspotify for more info about this
project.
"""

critiquebrainz/frontend/mapping/views.py
from flask import Blueprint, render_template, request, url_for, redirect, flash
from flask_login import login_required, current_user
from flask_babel import gettext
from werkzeug.exceptions import NotFound
import critiquebrainz.frontend.apis.spotify as spotify_api
from critiquebrainz.frontend.apis import musicbrainz, mbspotify
from urlparse import urlparse
import os.path
import string

mapping_bp = Blueprint('mapping', __name__)


@mapping_bp.route('/<uuid:release_group_id>')
def spotify_list(release_group_id):
    """This view lists all Spotify albums mapped to a specified release group."""
    spotify_mappings = mbspotify.mappings(str(release_group_id))

    # Converting Spotify URIs to IDs
    spotify_ids = []
    for mapping in spotify_mappings:
        spotify_ids.append(mapping[14:])

    if len(spotify_ids) > 0:
        spotify_albums = spotify_api.get_multiple_albums(spotify_ids)
    else:
        spotify_albums = []
    release_group = musicbrainz.get_release_group_by_id(release_group_id)
    if not release_group:
        raise NotFound("Can't find release group with a specified ID.")
    return render_template('mapping/list.html', spotify_albums=spotify_albums,
                           release_group=release_group)


@mapping_bp.route('/spotify/add')
def spotify():
    release_group_id = request.args.get('release_group_id')
    if not release_group_id:
        return redirect(url_for('frontend.index'))

    release_group = musicbrainz.get_release_group_by_id(release_group_id)
    if not release_group:
        flash(gettext("Only existing release groups can be mapped to Spotify!"), 'error')
        return redirect(url_for('search.index'))

    page = int(request.args.get('page', default=1))
    if page < 1:
        return redirect(url_for('.spotify'))
    limit = 16
    offset = (page - 1) * limit

    # Removing punctuation from the string
    punctuation_map = dict((ord(char), None) for char in string.punctuation)
    query = unicode(release_group['title']).translate(punctuation_map)
    # Searching...
    response = spotify_api.search(query, 'album', limit, offset).get('albums')
    return render_template('mapping/spotify.html', release_group=release_group, search_results=response.get('items'),
                           page=page, limit=limit, count=response.get('total'))


@mapping_bp.route('/spotify/confirm', methods=['GET', 'POST'])
@login_required
def spotify_confirm():
    """Confirmation page for adding new Spotify mapping."""
    release_group_id = request.args.get('release_group_id')
    release_group = musicbrainz.get_release_group_by_id(release_group_id)
    if not release_group:
        flash(gettext("Only existing release groups can be mapped to Spotify!"), 'error')
        return redirect(url_for('search.index'))

    spotify_ref = request.args.get('spotify_ref', default=None)
    if not spotify_ref:
        flash(gettext("You need to select an album from Spotify!"), 'error')
        return redirect(url_for('.spotify', release_group_id=release_group_id))

    spotify_id = parse_spotify_id(spotify_ref)
    if not spotify_id:
        flash(gettext("You need to specify a correct link to this album on Spotify!"), 'error')
        return redirect(url_for('.spotify', release_group_id=release_group_id))

    album = spotify_api.get_album(spotify_id)
    if not album or album.get('error'):
        flash(gettext("You need to specify existing album from Spotify!"), 'error')
        return redirect(url_for('.spotify', release_group_id=release_group_id))

    if request.method == 'POST':
        # TODO(roman): Check values that are returned by add_mapping (also take a look at related JS).
        mbspotify.add_mapping(release_group_id, 'spotify:album:%s' % spotify_id, current_user.id)
        flash(gettext("Spotify mapping has been added!"), 'success')
        return redirect(url_for('.spotify_list', release_group_id=release_group_id))

    return render_template('mapping/confirm.html', release_group=release_group, spotify_album=album)


@mapping_bp.route('/spotify/report', methods=['GET', 'POST'])
@login_required
def spotify_report():
    """Endpoint for reporting incorrect Spotify mappings.

    Shows confirmation page before submitting report to mbspotify.
    """
    release_group_id = request.args.get('release_group_id')
    spotify_id = request.args.get('spotify_id')
    spotify_uri = "spotify:album:" + spotify_id

    # Checking if release group exists
    release_group = musicbrainz.get_release_group_by_id(release_group_id)
    if not release_group:
        flash(gettext("Can't find release group with that ID!"), 'error')
        return redirect(url_for('.spotify_list', release_group_id=release_group_id))

    # Checking if release group is mapped to Spotify
    spotify_mappings = mbspotify.mappings(str(release_group_id))
    if not (spotify_uri in spotify_mappings):
        flash(gettext("This album is not mapped to Spotify yet!"), 'error')
        return redirect(url_for('.spotify_list', release_group_id=release_group_id))

    if request.method == 'POST':
        mbspotify.vote(release_group_id, spotify_uri, current_user.id)
        flash(gettext("Incorrect Spotify mapping has been reported. Thank you!"), 'success')
        return redirect(url_for('.spotify_list', release_group_id=release_group_id))

    else:
        album = spotify_api.get_album(spotify_id)
        if not album or album.get('error'):
            flash(gettext("You need to specify existing album from Spotify!"), 'error')
            return redirect(url_for('.spotify_list', release_group_id=release_group_id))

        return render_template('mapping/report.html', release_group=release_group, spotify_album=album)


def parse_spotify_id(spotify_ref):
    """Extracts Spotify ID out of reference to an album on Spotify.

    Supported reference types:
      - Spotify URI (spotify:album:6IH6co1QUS7uXoyPDv0rIr)
      - HTTP link (http://open.spotify.com/album/6IH6co1QUS7uXoyPDv0rIr)
    """
    # Spotify URI
    if spotify_ref.startswith('spotify:album:'):
        return spotify_ref[14:]

    # Link to Spotify
    # TODO(roman): Improve checking there. See https://bitbucket.org/metabrainz/critiquebrainz/pull-request/167/cb-115-support-for-different-types-of/activity#comment-2757329
    if spotify_ref.startswith('http://') or spotify_ref.startswith('https://'):
        if spotify_ref.endswith('/'):
            spotify_ref = spotify_ref[:-1]
        return os.path.split(urlparse(spotify_ref).path)[-1]

    # TODO(roman): Raise exception if failed to parse!

critiquebrainz/frontend/profile/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from flask_babel import gettext
from critiquebrainz.frontend.profile.forms import ProfileEditForm


profile_bp = Blueprint('profile_details', __name__)


@profile_bp.route('/edit', methods=['GET', 'POST'])
@login_required
def edit():
    form = ProfileEditForm()
    if form.validate_on_submit():
        current_user.update(display_name=form.display_name.data,
                            email=form.email.data,
                            show_gravatar=form.show_gravatar.data)
        flash(gettext("Profile updated."), 'success')
        return redirect(url_for('user.reviews', user_id=current_user.id))
    else:
        form.display_name.data = current_user.display_name
        form.email.data = current_user.email
        form.show_gravatar.data = current_user.show_gravatar
    return render_template('profile/edit.html', form=form)


@profile_bp.route('/delete', methods=['GET', 'POST'])
@login_required
def delete():
    if request.method == 'POST':
        current_user.delete()
        return redirect(url_for('frontend.index'))
    return render_template('profile/delete.html')

critiquebrainz/frontend/templates/user/base.html
{% extends 'base.html' %}

{% block title %}{{ user.display_name }} - CritiqueBrainz{% endblock %}

{% block content %}
  <div class="clearfix">
    <h2 class="pull-left"><img class="avatar" src="{{ user.avatar }}&s=32" /> {{ user.display_name }}</h2>
    {% if current_user.is_authenticated() and current_user == user %}
      <a href="{{ url_for('profile_details.edit') }}" class="btn btn-primary pull-right" style="margin-top: 20px;">
        <span class="glyphicon glyphicon-edit"></span> {{ _('Edit profile') }}
      </a>
    {% endif %}
  </div>

  <ul id="profile-navigation" class="nav nav-tabs" role="tablist">
    <li {{ 'class=active' if section=='reviews' }}><a href="{{ url_for('user.reviews', user_id=user.id) }}">{{ _('Reviews') }}</a></li>
    <li {{ 'class=active' if section=='info' }}><a href="{{ url_for('user.info', user_id=user.id) }}">{{ _('Info') }}</a></li>
  </ul>

  {% block profile_content %}{% endblock %}
{% endblock %}

critiquebrainz/frontend/templates/user/info.html
{% extends 'user/base.html' %}

{% block title %}{{ user.display_name }} - {{ _('Info') }} - CritiqueBrainz{% endblock %}

{% block profile_content %}
  {% if user.musicbrainz_id %}
    <div>
      <img src="{{ url_for('static', filename='favicons/musicbrainz-16.ico') }}" />
      <b><a href="https://musicbrainz.org/user/{{ user.musicbrainz_id }}">See profile on MusicBrainz</a></b>
    </div>
  {% endif %}

  <div class="row">

    <div class="col-md-7">
      <h4>{{ _('General information') }}</h4>
      <dl class="dl-horizontal">
        <dt>{{ _('Member since') }}</dt><dd>{{ user.created | date }}</dd>
        <dt>{{ _('User type') }}</dt><dd>{{ user.user_type.label }}</dd>
        <dt>{{ _('Karma') }}</dt><dd>{{ user.karma }}</dd>
        {% if current_user.is_authenticated() and current_user == user %}
          <dt>{{ _('Email') }}</dt><dd>{{ current_user.email }}</dd>
        {% endif %}
      </dl>
      {% if current_user.is_authenticated() and current_user == user %}
        <h4>{{ _('Limits') }}</h4>
        <dl class="dl-horizontal">
          <dt>{{ _('Reviews/day') }}</dt><dd>{{ current_user.user_type.reviews_per_day }}</dd>
          <dt>{{ _('Votes/day') }}</dt><dd>{{ current_user.user_type.votes_per_day }}</dd>
        </dl>
      {% endif %}
    </div>

    <div class="col-md-4">
      <h4>{{ _('Statistics') }}</h4>
      <h5>{{ _('Reviews') }}</h5>
      <dl class="dl-horizontal">
        <dt>{{ _('Today') }}</dt><dd>{{ user.stats.reviews_today }}</dd>
        <dt>{{ _('Last 7 days') }}</dt><dd>{{ user.stats.reviews_last_7_days }}</dd>
        <dt>{{ _('This month') }}</dt><dd>{{ user.stats.reviews_this_month }}</dd>
      </dl>
      <h5>{{ _('Votes') }}</h5>
      <dl class="dl-horizontal">
        <dt>{{ _('Today') }}</dt><dd>{{ user.stats.votes_today }}</dd>
        <dt>{{ _('Last 7 days') }}</dt><dd>{{ user.stats.votes_last_7_days }}</dd>
        <dt>{{ _('This month') }}</dt><dd>{{ user.stats.votes_this_month }}</dd>
      </dl>
    </div>

  </div>
{% endblock %}

critiquebrainz/frontend/templates/user/reviews.html
{% extends 'user/base.html' %}

{% block title %}{{ user.display_name }} - {{ _('Reviews') }} - CritiqueBrainz{% endblock %}

{% block profile_content %}
  {% if not reviews %}
    <p class="lead" style="text-align: center;">{{ _('No reviews found') }}</p>
  {% else %}
    <table class="table table-hover">
      <thead>
      <tr>
        {% if current_user.is_authenticated() and current_user == user %}<th><!-- State --></th>{% endif %}
        <th>{{ _('Artist') }}</th>
        <th>{{ _('Release group') }}</th>
        <th>{{ _('Created on') }}</th>
        <th>{{ _('Votes (+/-)') }}</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      {% for review in reviews %}
        {% set release_group = review.release_group | release_group_details %}
        <tr data-review-id="{{ review.id }}">
          {% if current_user.is_authenticated() and current_user == user %}
            <td align="right">
              {% if review.is_draft %}
                <span class="label label-default">{{ _('Draft') }}</span>
              {% else %}
                <span class="label label-primary">{{ _('Published') }}</span>
              {% endif %}
            </td>
          {% endif %}
          <td>{{ release_group['artist-credit-phrase'] | default(_('[Unknown artist]')) }}</td>
          <td>
            {{ release_group.title | default(_('[Unknown release group]')) }}
            {% if release_group['first-release-date'] %}
              <span class="text-muted">({{ release_group['first-release-date'][:4] }})</span>
            {% endif %}
          </td>
          <td>{{ review.created | date }}</td>
          <td>{{ review.votes_positive_count }}/{{ review.votes_negative_count }}</td>
          <td>
            <a class="btn btn-success btn-xs" href="{{ url_for('review.entity', id=review.id) }}">{{ _('Read') }}</a>
            {% if current_user.is_authenticated() and current_user == user %}
              <a class="btn btn-primary btn-xs" href="{{ url_for('review.edit', id=review.id) }}">{{ _('Edit') }}</a>
              <a class="btn btn-danger btn-xs" href="{{ url_for('review.delete', id=review.id) }}">{{ _('Delete') }}</a>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>

    {% if count > limit %}
      <ul class="pager">
        {% if page > 1 %}
          <li class="previous"><a href="{{ url_for('user.reviews', user_id=user.id, page=page-1) }}">&larr; {{ _('Newer') }}</a></li>
        {% endif %}
        {% if page-1 < count//limit %}
          <li class="next"><a href="{{ url_for('user.reviews', user_id=user.id, page=page+1) }}">{{ _('Older') }} &rarr;</a></li>
        {% endif %}
      </ul>
    {% endif %}
  {% endif %}
{% endblock %}