critiquebrainz/frontend/profile/applications/forms.py
from flask_wtf import Form
from flask_babel import gettext
from wtforms import StringField, validators


class ApplicationForm(Form):
    name = StringField(gettext('Application name'), [
        validators.DataRequired(message=gettext("Application name field is empty.")),
        validators.Length(min=3, message=gettext("Application name needs to be at least 3 characters long.")),
        validators.Length(max=64, message=gettext("Application name needs to be at most 64 characters long."))])
    desc = StringField(gettext('Description'), [
        validators.DataRequired(message=gettext("Client description field is empty.")),
        validators.Length(min=3, message=gettext("Client description needs to be at least 3 characters long.")),
        validators.Length(max=512, message=gettext("Client description needs to be at most 512 characters long."))])
    website = StringField(gettext('Homepage'), [
        validators.DataRequired(message=gettext("Homepage field is empty.")),
        validators.URL(message=gettext("Homepage is not a valid URI."))])
    redirect_uri = StringField(gettext('Authorization callback URL'), [
        validators.DataRequired(message=gettext("Authorization callback URL field is empty.")),
        validators.URL(message=gettext("Authorization callback URL is invalid."))])

critiquebrainz/frontend/profile/forms.py
from flask_wtf import Form
from flask_babel import gettext
from wtforms import StringField, BooleanField, validators
from wtforms.fields.html5 import EmailField


class ProfileEditForm(Form):
    display_name = StringField(gettext("Display name"), [
        validators.DataRequired(message=gettext("Display name field is empty.")),
        validators.Length(min=3, message=gettext("Display name needs to be at least 3 characters long.")),
        validators.Length(max=64, message=gettext("Display name needs to be at most 64 characters long."))])
    email = EmailField(gettext("Email"), [
        validators.Optional(strip_whitespace=False),
        validators.Email(message=gettext("Email field is not a valid email address."))])
    show_gravatar = BooleanField(gettext("Show my Gravatar"))

critiquebrainz/frontend/__init__.py
from flask import Flask
from flask_debugtoolbar import DebugToolbarExtension


def create_app(debug=None):
    app = Flask(__name__)

    # Configuration files
    import critiquebrainz.default_config
    app.config.from_object(critiquebrainz.default_config)
    app.config.from_pyfile('../config.py', silent=True)
    if debug is not None:
        app.debug = debug

    # Error handling
    import errors
    errors.init_error_handlers(app)

    # Logging
    from critiquebrainz import loggers
    loggers.init_loggers(app)

    if app.debug:
        # Debug toolbar
        DebugToolbarExtension(app)
        app.config['DEBUG_TB_TEMPLATE_EDITOR_ENABLED'] = True

    from flask_uuid import FlaskUUID
    FlaskUUID(app)

    from critiquebrainz.data import db
    db.init_app(app)

    # Memcached
    if 'MEMCACHED_SERVERS' in app.config:
        from critiquebrainz import cache
        cache.init(app.config['MEMCACHED_SERVERS'],
                   app.config['MEMCACHED_NAMESPACE'],
                   debug=1 if app.debug else 0)

    import babel
    babel.init_app(app)

    import login
    login.login_manager.init_app(app)
    from login.provider import MusicBrainzAuthentication
    login.mb_auth = MusicBrainzAuthentication(
        name='musicbrainz',
        client_id=app.config['MUSICBRAINZ_CLIENT_ID'],
        client_secret=app.config['MUSICBRAINZ_CLIENT_SECRET'],
        authorize_url="https://musicbrainz.org/oauth2/authorize",
        access_token_url="https://musicbrainz.org/oauth2/token",
        base_url="https://musicbrainz.org/")

    # APIs
    from apis import mbspotify
    mbspotify.init(app.config['MBSPOTIFY_BASE_URI'], app.config['MBSPOTIFY_ACCESS_KEY'])
    from apis import musicbrainz
    musicbrainz.init(app.config['MUSICBRAINZ_USERAGENT'], critiquebrainz.__version__,
                     hostname=app.config['MUSICBRAINZ_HOSTNAME'])

    # Template utilities
    app.jinja_env.add_extension('jinja2.ext.do')
    from critiquebrainz.utils import reformat_date, reformat_datetime, track_length
    app.jinja_env.filters['date'] = reformat_date
    app.jinja_env.filters['datetime'] = reformat_datetime
    app.jinja_env.filters['track_length'] = track_length
    app.jinja_env.filters['release_group_details'] = musicbrainz.get_release_group_by_id

    # Blueprints
    from views import frontend_bp
    from review.views import review_bp
    from search.views import search_bp
    from artist.views import artist_bp
    from release_group.views import release_group_bp
    from mapping.views import mapping_bp
    from user.views import user_bp
    from profile.views import profile_bp
    from profile.applications.views import profile_apps_bp
    from login.views import login_bp
    from oauth.views import oauth_bp
    from reports.views import reports_bp

    app.register_blueprint(frontend_bp)
    app.register_blueprint(review_bp, url_prefix='/review')
    app.register_blueprint(search_bp, url_prefix='/search')
    app.register_blueprint(artist_bp, url_prefix='/artist')
    app.register_blueprint(release_group_bp, url_prefix='/release-group')
    app.register_blueprint(mapping_bp, url_prefix='/mapping')
    app.register_blueprint(user_bp, url_prefix='/user')
    app.register_blueprint(profile_bp, url_prefix='/profile')
    app.register_blueprint(profile_apps_bp, url_prefix='/profile/applications')
    app.register_blueprint(login_bp, url_prefix='/login')
    app.register_blueprint(oauth_bp, url_prefix='/oauth')
    app.register_blueprint(reports_bp, url_prefix='/reports')

    return app

critiquebrainz/frontend/apis/__init__.py
"""
This package (api) provides modules to access external services:
 - MusicBrainz (with advanced relationship support)
 - Spotify
 - mbspotify

See documentation in each module for information about usage.
"""

critiquebrainz/frontend/artist/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_babel import gettext
from werkzeug.exceptions import BadRequest, NotFound
from critiquebrainz.frontend.apis import musicbrainz
from critiquebrainz.data.model.review import Review

artist_bp = Blueprint('artist', __name__)


@artist_bp.route('/<uuid:id>')
def entity(id):
    """Artist page.

    Displays release groups (split up into several sections depending on their
    type), artist information (type, members/member of, external links).
    """
    artist = musicbrainz.get_artist_by_id(id)
    if not artist:
        raise NotFound(gettext("Sorry, we couldn't find an artist with that MusicBrainz ID."))

    # Preparing artist-rels
    if 'band-members' in artist:
        artist['current_members'] = []
        artist['former_members'] = []
        for member in artist['band-members']:
            if 'ended' in member and member['ended'] == 'true':
                artist['former_members'].append(member)
            else:
                artist['current_members'].append(member)


    release_type = request.args.get('release_type', default='album')
    if release_type not in ['album', 'single', 'ep', 'broadcast', 'other']:  # supported release types
        raise BadRequest("Unsupported release type.")

    page = int(request.args.get('page', default=1))
    if page < 1:
        return redirect(url_for('.reviews'))
    limit = 20
    offset = (page - 1) * limit
    count, release_groups = musicbrainz.browse_release_groups(artist_id=id, release_types=[release_type],
                                                              limit=limit, offset=offset)
    for release_group in release_groups:
        # TODO(roman): Count reviews instead of fetching them.
        reviews, review_count = Review.list(release_group=release_group['id'], sort='created', limit=1)
        release_group['review_count'] = review_count
    return render_template('artist.html', id=id, artist=artist, release_type=release_type,
                           release_groups=release_groups, page=page, limit=limit, count=count)

critiquebrainz/frontend/login/__init__.py
"""
Package login provides authentication functionality for CritiqueBrainz.

It is based on OAuth2 protocol. MusicBrainz is the only supported provider.
"""
from flask import redirect, url_for
from flask_login import LoginManager, current_user
from flask_babel import gettext
from critiquebrainz.data.model.user import User
from werkzeug.exceptions import Unauthorized
from functools import wraps

mb_auth = None

login_manager = LoginManager()
login_manager.login_view = 'login.index'
login_manager.login_message = gettext(u"Please sign in to access this page.")
login_manager.localize_callback = gettext


@login_manager.user_loader
def load_user(user_id):
    return User.get(id=user_id)


def login_forbidden(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if current_user.is_anonymous() is False:
            return redirect(url_for('frontend.index'))
        return f(*args, **kwargs)

    return decorated


def admin_view(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not current_user.is_admin():
            raise Unauthorized(gettext('You must be an administrator to view this page.'))
        return f(*args, **kwargs)

    return decorated

critiquebrainz/frontend/login/views.py
from flask import Blueprint, request, redirect, render_template, url_for, session, flash
from flask_login import login_user, logout_user, login_required
from flask_babel import gettext
from critiquebrainz.frontend.login import mb_auth, login_forbidden

login_bp = Blueprint('login', __name__)


@login_bp.route('/')
@login_forbidden
def index():
    return render_template('login/login.html')


@login_bp.route('/musicbrainz')
@login_forbidden
def musicbrainz():
    session['next'] = request.args.get('next')
    return redirect(mb_auth.get_authentication_uri())


@login_bp.route('/musicbrainz/post')
@login_forbidden
def musicbrainz_post():
    """Callback endpoint."""
    if mb_auth.validate_post_login():
        login_user(mb_auth.get_user())
        next = session.get('next')
        if next:
            return redirect(next)
    else:
        flash(gettext("Login failed."), 'error')
    return redirect(url_for('frontend.index'))


@login_bp.route('/logout')
@login_required
def logout():
    logout_user()
    session.clear()
    return redirect(url_for('frontend.index'))

critiquebrainz/frontend/mapping/__init__.py
"""
Package mapping is basically an interface for mbspotify project.

It allows users to create mappings between release groups and albums on
Spotify. These mappings are then used to show embedded Spotify player on some
pages. See https://github.com/metabrainz/mbspotify for more info about this
project.
"""

critiquebrainz/frontend/oauth/views.py
from flask import Blueprint, render_template, redirect, request
from flask_login import login_required, current_user

from critiquebrainz.utils import build_url
from critiquebrainz.ws.oauth import oauth
from critiquebrainz.data.model.oauth_client import OAuthClient

oauth_bp = Blueprint('oauth', __name__)


@oauth_bp.route('/authorize', methods=['GET', 'POST'])
@login_required
def authorize_prompt():
    """OAuth 2.0 authorization endpoint."""
    response_type = request.args.get('response_type')
    client_id = request.args.get('client_id')
    redirect_uri = request.args.get('redirect_uri')
    scope = request.args.get('scope')
    state = request.args.get('state')

    if request.method == 'GET':  # Client requests access
        oauth.validate_authorization_request(client_id, response_type, redirect_uri, scope)
        client = OAuthClient.query.get(client_id)
        return render_template('oauth/prompt.html', client=client, scope=scope,
                               cancel_url=build_url(redirect_uri, dict(error='access_denied')))

    if request.method == 'POST':  # User grants access to the client
        oauth.validate_authorization_request(client_id, response_type, redirect_uri, scope)
        code = oauth.generate_grant(client_id, current_user.id, redirect_uri, scope)
        return redirect(build_url(redirect_uri, dict(code=code, state=state)))

critiquebrainz/frontend/profile/applications/views.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required, current_user
from flask_babel import gettext
from werkzeug.exceptions import NotFound
from critiquebrainz.data.model.oauth_client import OAuthClient
from critiquebrainz.data.model.oauth_token import OAuthToken
from critiquebrainz.frontend.profile.applications.forms import ApplicationForm


profile_apps_bp = Blueprint('profile_applications', __name__)


@profile_apps_bp.route('/')
@login_required
def index():
    return render_template('profile/applications/index.html',
                           applications=[c.to_dict() for c in current_user.clients],
                           tokens=[t.to_dict() for t in current_user.tokens])


@profile_apps_bp.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    """Create application."""
    form = ApplicationForm()
    if form.validate_on_submit():
        OAuthClient.create(user=current_user, name=form.name.data,
                           desc=form.desc.data, website=form.website.data,
                           redirect_uri=form.redirect_uri.data)
        flash(gettext('You have created an application!'), 'success')
        return redirect(url_for('.index'))
    return render_template('profile/applications/create.html', form=form)


@profile_apps_bp.route('/<client_id>/edit', methods=['GET', 'POST'])
@login_required
def edit(client_id):
    application = OAuthClient.query.get_or_404(client_id)
    if application.user != current_user:
        raise NotFound()
    form = ApplicationForm()
    if form.validate_on_submit():
        application.update(name=form.name.data, desc=form.desc.data,
                           website=form.website.data, redirect_uri=form.redirect_uri.data)
        flash(gettext("You have updated an application!"), 'success')
        return redirect(url_for('.index'))
    else:
        form.name.data = application.name
        form.desc.data = application.desc
        form.website.data = application.website
        form.redirect_uri.data = application.redirect_uri
    return render_template('profile/applications/edit.html', form=form)


@profile_apps_bp.route('/<client_id>/delete')
@login_required
def delete(client_id):
    client = OAuthClient.query.get_or_404(client_id)
    if client.user != current_user:
        raise NotFound()
    client.delete()

    flash(gettext('You have deleted an application.'), 'success')
    return redirect(url_for('.index'))


@profile_apps_bp.route('/<client_id>/token/delete')
@login_required
def token_delete(client_id):
    OAuthToken.purge_tokens(client_id=client_id, user_id=current_user.id)
    return redirect(url_for('.index'))

critiquebrainz/frontend/profile/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from flask_babel import gettext
from critiquebrainz.frontend.profile.forms import ProfileEditForm


profile_bp = Blueprint('profile_details', __name__)


@profile_bp.route('/edit', methods=['GET', 'POST'])
@login_required
def edit():
    form = ProfileEditForm()
    if form.validate_on_submit():
        current_user.update(display_name=form.display_name.data,
                            email=form.email.data,
                            show_gravatar=form.show_gravatar.data)
        flash(gettext("Profile updated."), 'success')
        return redirect(url_for('user.reviews', user_id=current_user.id))
    else:
        form.display_name.data = current_user.display_name
        form.email.data = current_user.email
        form.show_gravatar.data = current_user.show_gravatar
    return render_template('profile/edit.html', form=form)


@profile_bp.route('/delete', methods=['GET', 'POST'])
@login_required
def delete():
    if request.method == 'POST':
        current_user.delete()
        return redirect(url_for('frontend.index'))
    return render_template('profile/delete.html')

critiquebrainz/frontend/release_group/views.py
from flask import Blueprint, render_template, request
from flask_login import current_user
from flask_babel import gettext
from critiquebrainz.frontend.apis import musicbrainz, mbspotify
from critiquebrainz.data.model.review import Review
from werkzeug.exceptions import NotFound


release_group_bp = Blueprint('release_group', __name__)


@release_group_bp.route('/<uuid:id>')
def entity(id):
    id = str(id)
    release_group = musicbrainz.get_release_group_by_id(id)
    if not release_group:
        raise NotFound(gettext("Sorry, we couldn't find a release group with that MusicBrainz ID."))
    if len(release_group['release-list']) > 0:
        release = musicbrainz.get_release_by_id(release_group['release-list'][0]['id'])
    else:
        release = None
    spotify_mappings = mbspotify.mappings(id)
    limit = int(request.args.get('limit', default=10))
    offset = int(request.args.get('offset', default=0))
    if current_user.is_authenticated():
        my_reviews, my_count = Review.list(release_group=id, user_id=current_user.id)
        if my_count != 0:
            my_review = my_reviews[0]
        else:
            my_review = None
    else:
        my_review = None
    reviews, count = Review.list(release_group=id, sort='rating', limit=limit, offset=offset)
    return render_template('release_group.html', id=id, release_group=release_group, reviews=reviews,
                           release=release, my_review=my_review, spotify_mappings=spotify_mappings,
                           limit=limit, offset=offset, count=count)

critiquebrainz/frontend/templates/profile/applications/create.html
{% extends 'base.html' %}

{% block title %}{{ _('Create new application') }} - CritiqueBrainz{% endblock %}

{% block content %}
  <h2>{{ _('Create new application') }}</h2>
  <hr />

  {% for field in form.errors %}
    {% for error in form.errors[field] %}
      <div class="alert alert-danger">{{ error }}</div>
    {% endfor %}
  {% endfor %}

  <form method="POST" class="form-horizontal" role="form">
    {{ form.hidden_tag() }}
    <fieldset>
      <div class="form-group">
        <label class="col-sm-3 control-label">{{ form.name.label.text }}</label>
        <div class="col-sm-5">{{ form.name(class="form-control", required="required") }}</div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label">{{ form.desc.label.text }}</label>
        <div class="col-sm-5">{{ form.desc(class="form-control", required="required") }}</div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label">{{ form.website.label.text }}</label>
        <div class="col-sm-5">{{ form.website(class="form-control", required="required") }}</div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label">{{ form.redirect_uri.label.text }}</label>
        <div class="col-sm-5">{{ form.redirect_uri(class="form-control", required="required") }}</div>
      </div>
    </fieldset>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-10">
        <button type="submit" class="btn btn-primary">{{ _('Create application') }}</button>
      </div>
    </div>
  </form>
{% endblock %}

critiquebrainz/frontend/templates/profile/applications/edit.html
{% extends 'base.html' %}

{% block title %}{{ _('Edit application %(name)s', name=form.name.data) }} - CritiqueBrainz{% endblock %}

{% block content %}
  <h2>{{ _('Edit application %(name)s', name=form.name.data) }}</h2>
  <hr />

  {% for field in form.errors %}
    {% for error in form.errors[field] %}
      <div class="alert alert-danger">{{ error }}</div>
    {% endfor %}
  {% endfor %}

  <form method="POST" class="form-horizontal" role="form">
    {{ form.hidden_tag() }}
    <fieldset>
      <div class="form-group">
        <label class="col-sm-3 control-label">{{ form.name.label.text }}</label>
        <div class="col-sm-5">{{ form.name(class="form-control", required="required") }}</div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label">{{ form.desc.label.text }}</label>
        <div class="col-sm-5">{{ form.desc(class="form-control", required="required") }}</div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label">{{ form.website.label.text }}</label>
        <div class="col-sm-5">{{ form.website(class="form-control", required="required") }}</div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label">{{ form.redirect_uri.label.text }}</label>
        <div class="col-sm-5">{{ form.redirect_uri(class="form-control", required="required") }}</div>
      </div>
    </fieldset>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-10">
        <button type="submit" class="btn btn-primary">{{ _('Save changes') }}</button>
      </div>
    </div>
  </form>
{% endblock %}

critiquebrainz/frontend/templates/profile/applications/index.html
{% extends 'base.html' %}

{% block title %}{{ _('Applications') }} - CritiqueBrainz{% endblock %}

{% block content %}
  <h2>{{ _('Applications') }}</h2>

  <div class="clearfix">
    <h3 class="pull-left">{{ _('Your applications') }}</h3>
    <a href="{{ url_for('profile_applications.create') }}" class="btn btn-success pull-right" style="margin-top:12px;">
      <span class="glyphicon glyphicon-asterisk"></span> {{ _('Create new application') }}
    </a>
  </div>
  {% if not applications %}
    <p class="lead" style="text-align: center;">{{ _('No applications found') }}</p>
  {% else %}
    <table class="table table-hover">
      <thead>
      <tr>
        <th>{{ _('Name') }}</th>
        <th>{{ _('Website') }}</th>
        <th>{{ _('Client ID') }}</th>
        <th>{{ _('Client secret') }}</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      {% for app in applications %}
        <tr>
          <td>{{ app.name }}</td>
          <td>{{ app.website }}</td>
          <td>{{ app.client_id }}</td>
          <td>{{ app.client_secret }}</td>
          <td>
            <a class="btn btn-primary btn-xs" href="{{ url_for('profile_applications.edit', client_id=app.client_id) }}">{{ _('Modify') }}</a>
            <a class="btn btn-danger btn-xs" href="{{ url_for('profile_applications.delete', client_id=app.client_id) }}">{{ _('Delete') }}</a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% endif %}
  <div class="alert alert-info">{{ _('Developer documentation is available at %(link)s.', link='<a href="https://critiquebrainz.readthedocs.org/">critiquebrainz.readthedocs.org</a>'|safe) }}</div>

  <hr />

  <h3>{{ _('Authorized applications') }}</h3>
  {% if not tokens %}
    <p class="lead" style="text-align: center;">{{ _('No authorized applications found') }}</p>
  {% else %}
    <table class="table table-hover">
      <thead>
        <tr>
          <th>{{ _('Name') }}</th>
          <th>{{ _('Website') }}</th>
          <th>{{ _('Access') }}</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for token in tokens %}
          <tr>
            <td><b>{{ token.client.name }}</b></td>
            <td>{{ token.client.website }}</td>
            <td>
              {% if token.scopes %}
                <ul>
                  {% set scopes = token.scopes.split() %}
                  {% from 'macros.html' import scope_desc %}
                  {% for scope in scopes %}
                    <li>{{ scope_desc(scope) }}</li>
                  {% endfor %}
                </ul>
              {% else %}
                {{ _('No special requirements') }}
              {% endif %}
            </td>
            <td>
              <a class="btn btn-danger btn-xs" href="{{ url_for('profile_applications.token_delete', client_id=token.client.client_id) }}">{{ _('Revoke access') }}</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}
{% endblock %}