critiquebrainz/frontend/__init__.py
from flask import Flask
from flask_debugtoolbar import DebugToolbarExtension


def create_app(debug=None):
    app = Flask(__name__)

    # Configuration files
    import critiquebrainz.default_config
    app.config.from_object(critiquebrainz.default_config)
    app.config.from_pyfile('../config.py', silent=True)
    if debug is not None:
        app.debug = debug

    # Error handling
    import errors
    errors.init_error_handlers(app)

    # Logging
    from critiquebrainz import loggers
    loggers.init_loggers(app)

    if app.debug:
        # Debug toolbar
        DebugToolbarExtension(app)
        app.config['DEBUG_TB_TEMPLATE_EDITOR_ENABLED'] = True

    from flask_uuid import FlaskUUID
    FlaskUUID(app)

    from critiquebrainz.data import db
    db.init_app(app)

    # Memcached
    if 'MEMCACHED_SERVERS' in app.config:
        from critiquebrainz import cache
        cache.init(app.config['MEMCACHED_SERVERS'],
                   app.config['MEMCACHED_NAMESPACE'],
                   debug=1 if app.debug else 0)

    import babel
    babel.init_app(app)

    import login
    login.login_manager.init_app(app)
    from login.provider import MusicBrainzAuthentication
    login.mb_auth = MusicBrainzAuthentication(
        name='musicbrainz',
        client_id=app.config['MUSICBRAINZ_CLIENT_ID'],
        client_secret=app.config['MUSICBRAINZ_CLIENT_SECRET'],
        authorize_url="https://musicbrainz.org/oauth2/authorize",
        access_token_url="https://musicbrainz.org/oauth2/token",
        base_url="https://musicbrainz.org/")

    # APIs
    from apis import mbspotify
    mbspotify.init(app.config['MBSPOTIFY_BASE_URI'], app.config['MBSPOTIFY_ACCESS_KEY'])
    from apis import musicbrainz
    musicbrainz.init(app.config['MUSICBRAINZ_USERAGENT'], critiquebrainz.__version__,
                     hostname=app.config['MUSICBRAINZ_HOSTNAME'])

    # Template utilities
    app.jinja_env.add_extension('jinja2.ext.do')
    from critiquebrainz.utils import reformat_date, reformat_datetime, track_length
    app.jinja_env.filters['date'] = reformat_date
    app.jinja_env.filters['datetime'] = reformat_datetime
    app.jinja_env.filters['track_length'] = track_length
    app.jinja_env.filters['release_group_details'] = musicbrainz.get_release_group_by_id

    # Blueprints
    from views import frontend_bp
    from review.views import review_bp
    from search.views import search_bp
    from artist.views import artist_bp
    from release_group.views import release_group_bp
    from mapping.views import mapping_bp
    from user.views import user_bp
    from profile.views import profile_bp
    from profile.applications.views import profile_apps_bp
    from login.views import login_bp
    from oauth.views import oauth_bp
    from reports.views import reports_bp

    app.register_blueprint(frontend_bp)
    app.register_blueprint(review_bp, url_prefix='/review')
    app.register_blueprint(search_bp, url_prefix='/search')
    app.register_blueprint(artist_bp, url_prefix='/artist')
    app.register_blueprint(release_group_bp, url_prefix='/release-group')
    app.register_blueprint(mapping_bp, url_prefix='/mapping')
    app.register_blueprint(user_bp, url_prefix='/user')
    app.register_blueprint(profile_bp, url_prefix='/profile')
    app.register_blueprint(profile_apps_bp, url_prefix='/profile/applications')
    app.register_blueprint(login_bp, url_prefix='/login')
    app.register_blueprint(oauth_bp, url_prefix='/oauth')
    app.register_blueprint(reports_bp, url_prefix='/reports')

    return app

critiquebrainz/frontend/artist/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_babel import gettext
from werkzeug.exceptions import BadRequest, NotFound
from critiquebrainz.frontend.apis import musicbrainz
from critiquebrainz.data.model.review import Review

artist_bp = Blueprint('artist', __name__)


@artist_bp.route('/<uuid:id>')
def entity(id):
    """Artist page.

    Displays release groups (split up into several sections depending on their
    type), artist information (type, members/member of, external links).
    """
    artist = musicbrainz.get_artist_by_id(id)
    if not artist:
        raise NotFound(gettext("Sorry, we couldn't find an artist with that MusicBrainz ID."))

    # Preparing artist-rels
    if 'band-members' in artist:
        artist['current_members'] = []
        artist['former_members'] = []
        for member in artist['band-members']:
            if 'ended' in member and member['ended'] == 'true':
                artist['former_members'].append(member)
            else:
                artist['current_members'].append(member)


    release_type = request.args.get('release_type', default='album')
    if release_type not in ['album', 'single', 'ep', 'broadcast', 'other']:  # supported release types
        raise BadRequest("Unsupported release type.")

    page = int(request.args.get('page', default=1))
    if page < 1:
        return redirect(url_for('.reviews'))
    limit = 20
    offset = (page - 1) * limit
    count, release_groups = musicbrainz.browse_release_groups(artist_id=id, release_types=[release_type],
                                                              limit=limit, offset=offset)
    for release_group in release_groups:
        # TODO(roman): Count reviews instead of fetching them.
        reviews, review_count = Review.list(release_group=release_group['id'], sort='created', limit=1)
        release_group['review_count'] = review_count
    return render_template('artist.html', id=id, artist=artist, release_type=release_type,
                           release_groups=release_groups, page=page, limit=limit, count=count)

critiquebrainz/frontend/login/views.py
from flask import Blueprint, request, redirect, render_template, url_for, session, flash
from flask_login import login_user, logout_user, login_required
from flask_babel import gettext
from critiquebrainz.frontend.login import mb_auth, login_forbidden

login_bp = Blueprint('login', __name__)


@login_bp.route('/')
@login_forbidden
def index():
    return render_template('login/login.html')


@login_bp.route('/musicbrainz')
@login_forbidden
def musicbrainz():
    session['next'] = request.args.get('next')
    return redirect(mb_auth.get_authentication_uri())


@login_bp.route('/musicbrainz/post')
@login_forbidden
def musicbrainz_post():
    """Callback endpoint."""
    if mb_auth.validate_post_login():
        login_user(mb_auth.get_user())
        next = session.get('next')
        if next:
            return redirect(next)
    else:
        flash(gettext("Login failed."), 'error')
    return redirect(url_for('frontend.index'))


@login_bp.route('/logout')
@login_required
def logout():
    logout_user()
    session.clear()
    return redirect(url_for('frontend.index'))

critiquebrainz/frontend/mapping/views.py
from flask import Blueprint, render_template, request, url_for, redirect, flash
from flask_login import login_required, current_user
from flask_babel import gettext
from werkzeug.exceptions import NotFound
import critiquebrainz.frontend.apis.spotify as spotify_api
from critiquebrainz.frontend.apis import musicbrainz, mbspotify
from urlparse import urlparse
import os.path
import string

mapping_bp = Blueprint('mapping', __name__)


@mapping_bp.route('/<uuid:release_group_id>')
def spotify_list(release_group_id):
    """This view lists all Spotify albums mapped to a specified release group."""
    spotify_mappings = mbspotify.mappings(str(release_group_id))

    # Converting Spotify URIs to IDs
    spotify_ids = []
    for mapping in spotify_mappings:
        spotify_ids.append(mapping[14:])

    if len(spotify_ids) > 0:
        spotify_albums = spotify_api.get_multiple_albums(spotify_ids)
    else:
        spotify_albums = []
    release_group = musicbrainz.get_release_group_by_id(release_group_id)
    if not release_group:
        raise NotFound("Can't find release group with a specified ID.")
    return render_template('mapping/list.html', spotify_albums=spotify_albums,
                           release_group=release_group)


@mapping_bp.route('/spotify/add')
def spotify():
    release_group_id = request.args.get('release_group_id')
    if not release_group_id:
        return redirect(url_for('frontend.index'))

    release_group = musicbrainz.get_release_group_by_id(release_group_id)
    if not release_group:
        flash(gettext("Only existing release groups can be mapped to Spotify!"), 'error')
        return redirect(url_for('search.index'))

    page = int(request.args.get('page', default=1))
    if page < 1:
        return redirect(url_for('.spotify'))
    limit = 16
    offset = (page - 1) * limit

    # Removing punctuation from the string
    punctuation_map = dict((ord(char), None) for char in string.punctuation)
    query = unicode(release_group['title']).translate(punctuation_map)
    # Searching...
    response = spotify_api.search(query, 'album', limit, offset).get('albums')
    return render_template('mapping/spotify.html', release_group=release_group, search_results=response.get('items'),
                           page=page, limit=limit, count=response.get('total'))


@mapping_bp.route('/spotify/confirm', methods=['GET', 'POST'])
@login_required
def spotify_confirm():
    """Confirmation page for adding new Spotify mapping."""
    release_group_id = request.args.get('release_group_id')
    release_group = musicbrainz.get_release_group_by_id(release_group_id)
    if not release_group:
        flash(gettext("Only existing release groups can be mapped to Spotify!"), 'error')
        return redirect(url_for('search.index'))

    spotify_ref = request.args.get('spotify_ref', default=None)
    if not spotify_ref:
        flash(gettext("You need to select an album from Spotify!"), 'error')
        return redirect(url_for('.spotify', release_group_id=release_group_id))

    spotify_id = parse_spotify_id(spotify_ref)
    if not spotify_id:
        flash(gettext("You need to specify a correct link to this album on Spotify!"), 'error')
        return redirect(url_for('.spotify', release_group_id=release_group_id))

    album = spotify_api.get_album(spotify_id)
    if not album or album.get('error'):
        flash(gettext("You need to specify existing album from Spotify!"), 'error')
        return redirect(url_for('.spotify', release_group_id=release_group_id))

    if request.method == 'POST':
        # TODO(roman): Check values that are returned by add_mapping (also take a look at related JS).
        mbspotify.add_mapping(release_group_id, 'spotify:album:%s' % spotify_id, current_user.id)
        flash(gettext("Spotify mapping has been added!"), 'success')
        return redirect(url_for('.spotify_list', release_group_id=release_group_id))

    return render_template('mapping/confirm.html', release_group=release_group, spotify_album=album)


@mapping_bp.route('/spotify/report', methods=['GET', 'POST'])
@login_required
def spotify_report():
    """Endpoint for reporting incorrect Spotify mappings.

    Shows confirmation page before submitting report to mbspotify.
    """
    release_group_id = request.args.get('release_group_id')
    spotify_id = request.args.get('spotify_id')
    spotify_uri = "spotify:album:" + spotify_id

    # Checking if release group exists
    release_group = musicbrainz.get_release_group_by_id(release_group_id)
    if not release_group:
        flash(gettext("Can't find release group with that ID!"), 'error')
        return redirect(url_for('.spotify_list', release_group_id=release_group_id))

    # Checking if release group is mapped to Spotify
    spotify_mappings = mbspotify.mappings(str(release_group_id))
    if not (spotify_uri in spotify_mappings):
        flash(gettext("This album is not mapped to Spotify yet!"), 'error')
        return redirect(url_for('.spotify_list', release_group_id=release_group_id))

    if request.method == 'POST':
        mbspotify.vote(release_group_id, spotify_uri, current_user.id)
        flash(gettext("Incorrect Spotify mapping has been reported. Thank you!"), 'success')
        return redirect(url_for('.spotify_list', release_group_id=release_group_id))

    else:
        album = spotify_api.get_album(spotify_id)
        if not album or album.get('error'):
            flash(gettext("You need to specify existing album from Spotify!"), 'error')
            return redirect(url_for('.spotify_list', release_group_id=release_group_id))

        return render_template('mapping/report.html', release_group=release_group, spotify_album=album)


def parse_spotify_id(spotify_ref):
    """Extracts Spotify ID out of reference to an album on Spotify.

    Supported reference types:
      - Spotify URI (spotify:album:6IH6co1QUS7uXoyPDv0rIr)
      - HTTP link (http://open.spotify.com/album/6IH6co1QUS7uXoyPDv0rIr)
    """
    # Spotify URI
    if spotify_ref.startswith('spotify:album:'):
        return spotify_ref[14:]

    # Link to Spotify
    # TODO(roman): Improve checking there. See https://bitbucket.org/metabrainz/critiquebrainz/pull-request/167/cb-115-support-for-different-types-of/activity#comment-2757329
    if spotify_ref.startswith('http://') or spotify_ref.startswith('https://'):
        if spotify_ref.endswith('/'):
            spotify_ref = spotify_ref[:-1]
        return os.path.split(urlparse(spotify_ref).path)[-1]

    # TODO(roman): Raise exception if failed to parse!

critiquebrainz/frontend/profile/applications/views.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required, current_user
from flask_babel import gettext
from werkzeug.exceptions import NotFound
from critiquebrainz.data.model.oauth_client import OAuthClient
from critiquebrainz.data.model.oauth_token import OAuthToken
from critiquebrainz.frontend.profile.applications.forms import ApplicationForm


profile_apps_bp = Blueprint('profile_applications', __name__)


@profile_apps_bp.route('/')
@login_required
def index():
    return render_template('profile/applications/index.html',
                           applications=[c.to_dict() for c in current_user.clients],
                           tokens=[t.to_dict() for t in current_user.tokens])


@profile_apps_bp.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    """Create application."""
    form = ApplicationForm()
    if form.validate_on_submit():
        OAuthClient.create(user=current_user, name=form.name.data,
                           desc=form.desc.data, website=form.website.data,
                           redirect_uri=form.redirect_uri.data)
        flash(gettext('You have created an application!'), 'success')
        return redirect(url_for('.index'))
    return render_template('profile/applications/create.html', form=form)


@profile_apps_bp.route('/<client_id>/edit', methods=['GET', 'POST'])
@login_required
def edit(client_id):
    application = OAuthClient.query.get_or_404(client_id)
    if application.user != current_user:
        raise NotFound()
    form = ApplicationForm()
    if form.validate_on_submit():
        application.update(name=form.name.data, desc=form.desc.data,
                           website=form.website.data, redirect_uri=form.redirect_uri.data)
        flash(gettext("You have updated an application!"), 'success')
        return redirect(url_for('.index'))
    else:
        form.name.data = application.name
        form.desc.data = application.desc
        form.website.data = application.website
        form.redirect_uri.data = application.redirect_uri
    return render_template('profile/applications/edit.html', form=form)


@profile_apps_bp.route('/<client_id>/delete')
@login_required
def delete(client_id):
    client = OAuthClient.query.get_or_404(client_id)
    if client.user != current_user:
        raise NotFound()
    client.delete()

    flash(gettext('You have deleted an application.'), 'success')
    return redirect(url_for('.index'))


@profile_apps_bp.route('/<client_id>/token/delete')
@login_required
def token_delete(client_id):
    OAuthToken.purge_tokens(client_id=client_id, user_id=current_user.id)
    return redirect(url_for('.index'))

critiquebrainz/frontend/release_group/views.py
from flask import Blueprint, render_template, request
from flask_login import current_user
from flask_babel import gettext
from critiquebrainz.frontend.apis import musicbrainz, mbspotify
from critiquebrainz.data.model.review import Review
from werkzeug.exceptions import NotFound


release_group_bp = Blueprint('release_group', __name__)


@release_group_bp.route('/<uuid:id>')
def entity(id):
    id = str(id)
    release_group = musicbrainz.get_release_group_by_id(id)
    if not release_group:
        raise NotFound(gettext("Sorry, we couldn't find a release group with that MusicBrainz ID."))
    if len(release_group['release-list']) > 0:
        release = musicbrainz.get_release_by_id(release_group['release-list'][0]['id'])
    else:
        release = None
    spotify_mappings = mbspotify.mappings(id)
    limit = int(request.args.get('limit', default=10))
    offset = int(request.args.get('offset', default=0))
    if current_user.is_authenticated():
        my_reviews, my_count = Review.list(release_group=id, user_id=current_user.id)
        if my_count != 0:
            my_review = my_reviews[0]
        else:
            my_review = None
    else:
        my_review = None
    reviews, count = Review.list(release_group=id, sort='rating', limit=limit, offset=offset)
    return render_template('release_group.html', id=id, release_group=release_group, reviews=reviews,
                           release=release, my_review=my_review, spotify_mappings=spotify_mappings,
                           limit=limit, offset=offset, count=count)

critiquebrainz/frontend/templates/about.html
{% extends 'base.html' %}

{% block title %}{{ _('About CritiqueBrainz') }}{% endblock %}

{% block content %}
<h2>{{ _('About') }}</h2>

<h3>{{ _('What is CritiqueBrainz?') }}</h3>
<p>
  {{ _('<strong>CritiqueBrainz is a repository for Creative Commons licensed music reviews.</strong>
  Here you can read what others have written about an album or write your own review!
  It is based on data from MusicBrainz - open music encyclopedia.') }}
</p>

<h3>{{ _('What is it for?') }}</h3>
<p>
  {{ _('Projects like Wikipedia and MusicBrainz are good at aggregating information about
  music, but not suited for expressing opinions about it. That\'s not their purpose.
  CritiqueBrainz fills the gap between music critics and raw data.') }}
</p>
<p>
  {{ _('This is an open platform. That means everyone - including you - can participate
  and contribute. If you are good at writing and want to share your thoughts about
  an album - feel free to write a new review. If that\'s not your thing and you just
  want to read opinions - that\'s fine too.') }}
</p>
<p>
  {{ _('After reading a review you can mark it as useful or not. That will help other
  music enthusiasts like you find good reviews.') }}
</p>

{% endblock %}

critiquebrainz/frontend/templates/macros.html
{% macro print_error(message, category) -%}
  {% if category == "error" %}
    {% set head = _("Error!") %}
    {% set alert_class="alert-danger" %}
  {% elif category == "warning" %}
    {% set head = _("Warning!") %}
    {% set alert_class="alert-warning" %}
  {% elif category == "success" %}
    {% set head = _("Success!") %}
    {% set alert_class="alert-success" %}
  {% else %}
    {% set head = _("Notice!") %}
    {% set alert_class="alert-info" %}
  {% endif %}
<div class="alert {{ alert_class }}">
  <strong>{{ head }}</strong>
  {{ message }}
</div>
{% endmacro %}

{% macro scope_desc(scope) %}
  {% if scope == "user" %}
    <strong class="text-danger">
      <abbr title="{{ _('Modify profile info and delete your profile.') }}">{{ _('Profile data') }}</abbr>
    </strong>
  {% elif scope == "review" %}
    <abbr title="{{ _('Create and modify your reviews.') }}">{{ _('Reviews') }}</abbr>
  {% elif scope == "client" %}
    <abbr title="{{ _('Modify your applications (create, edit, delete).') }}">{{ _('Applications') }}</abbr>
  {% elif scope == "authorization" %}
    <strong class="text-danger">
      <abbr title="{{ _('Manage access to your profile for other apps (can allow complete access to your profile and remove existing access authorizations).') }}">{{ _('Authorization') }}</abbr>
    </strong>
  {% elif scope == "vote" %}
    <abbr title="{{ _('Submit and delete your votes.') }}">{{ _('Review votes') }}</abbr>
  {% endif %}
{% endmacro %}

critiquebrainz/frontend/templates/navbar.html
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#cb-navbar-collapse">
        <span class="sr-only">{{ _('Toggle navigation') }}</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand logo" href="{{ url_for('frontend.index') }}">
        <img src="{{ url_for('static', filename='img/navbar_logo.svg') }}" alt="CritiqueBrainz" />
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="cb-navbar-collapse">
      <ul class="nav navbar-nav">
        {% if not error %} {# Not showing this stuff on error pages. If attempt to load user info fails there, page will not render. #}
          {% if not current_user or current_user.is_anonymous() %}
            <li><a href="{{ url_for('login.index') }}">{{ _('Sign in') }}</a></li>
          {% else %}
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                {{ current_user.display_name }} <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('user.reviews', user_id=current_user.id) }}">{{ _('Profile') }}</a></li>
                <li><a href="{{ url_for('profile_applications.index') }}">{{ _('Applications') }}</a></li>
                <li class="divider"></li>
                <li><a href="{{ url_for('login.logout') }}">{{ _('Sign out') }}</a></li>
              </ul>
            </li>
          {% endif %}
        {% endif %}
        <li><a href="{{ url_for('review.browse') }}">{{ _('Browse reviews') }}</a></li>
        <li><a href="{{ url_for('review.create') }}">{{ _('Write a review') }}</a></li>
        <li class="hidden-md"><a href="{{ url_for('frontend.about') }}">{{ _('About') }}</a></li>
      </ul>
      <form class="navbar-form navbar-right" role="search" method="GET" action="{{ url_for('search.index') }}">
        <div class="form-group">
          <input type="text" name="query" class="form-control input-sm" placeholder="{{ _('Search') }}">
        </div>
        <div class="form-group">
          <select id="type-selector" name="type" class="form-control input-sm">
            <option value="artist">{{ _('Artist') }}</option>
            <option value="release-group">{{ _('Release group') }}</option>
          </select>
        </div>
        <button type="submit" class="btn btn-default input-sm"><span class="glyphicon glyphicon-search"></span></button>
      </form>
    </div>
  </div>
</nav>

critiquebrainz/frontend/templates/release_group.html
{% extends 'base.html' %}

{% block title %}
{{ _('Release group "%(title)s" by %(artist)s', title=release_group.title, artist=release_group['artist-credit-phrase']) }}
- CritiqueBrainz
{% endblock %}

{% block content %}
<div class="clearfix">
  <h2 class="pull-left">
    {% set artist = [] %}
    {% for credit in release_group['artist-credit'] %}
      {% if credit.artist %}
        {% do artist.append('<a href="%s">'|safe % url_for('artist.entity', id=credit.artist.id) ~ credit.artist.name ~ '</a>'|safe) %}
      {% else %}
        {% do artist.append(credit) %}
      {% endif %}
    {% endfor %}

    {{ _('%(album)s by %(artist)s', album = release_group.title, artist = artist|join()) }}

    {% if release_group['first-release-date'] %}
      <small>{{ release_group['first-release-date'][:4] }}</small>
    {% endif %}
  </h2>

  {% if not my_review %}
    <a id="write-review" href="{{ url_for('review.create', release_group=id) }}"
       role="button" class="btn btn-success pull-right">
      <span class="glyphicon glyphicon-asterisk"></span> {{ _('Write a review') }}
    </a>
  {% else %}
    <a id="edit-review" href="{{ url_for('review.edit', id=my_review.id) }}"
       role="button" class="btn btn-primary pull-right">
      <span class="glyphicon glyphicon-edit"></span> {{ _('Edit my review') }}
    </a>
  {% endif %}
</div>

<div id="release-group-details" class="row">
  <div class="col-md-3">
    <img id="cover-art" class="img-responsive">
    <script>
      $("img").last()
          .on("error", function () { $(this).attr("src", "/static/img/missing-art.png"); })
          .attr("src", "//coverartarchive.org/release-group/{{ id }}/front-250");
    </script>
    <div id="spotify-play-button">
      {% if spotify_mappings %}
        <iframe src="https://embed.spotify.com/?uri={{ spotify_mappings[0] }}&theme=white"
                width="100%" height="80" frameborder="0" allowtransparency="true"></iframe>
        <em><small><a class="text-muted" href="{{ url_for('mapping.spotify_list', release_group_id=id) }}">{{ _('View Spotify mapping information') }}</a></small></em>
      {% else %}
        <span class="text-muted">
          {{ _('We don\'t have a mapping between this release group and Spotify.
          Please help us find the right album.') }}
        </span>
        <div style="text-align:center;font-weight:bold;"><a style="font-size:16px;" href="{{ url_for('mapping.spotify', release_group_id=id) }}" rel="nofollow">{{ _('Match this!') }}</a></div>
      {% endif %}
    </div>
  </div>
  <div class="col-md-6">
    <h4 style="margin-bottom:0;">{{ _('Reviews') }}</h4>
    {% if not reviews %}
      <p class="lead" style="text-align: center;">{{ _('No reviews found') }}</p>
    {% else %}
      <table class="table table-condensed table-hover">
        <thead>
          <tr>
            <th></th>
            <th>{{ _('Published on') }}</th>
            <th>{{ _('Votes (+/-)') }}</th>
          </tr>
        </thead>
        <tbody>
          {% for review in reviews %}
            <tr data-review-id="{{ review.id }}">
              <td>
                <a href="{{ url_for('review.entity', id=review.id) }}">
                  {{ _('by %(reviewer)s', reviewer='<img class="avatar" src="%s&s=16" /> '|safe % review.user.avatar + review.user.display_name) }}
                </a>
              </td>
              <td>{{ review.created | date }}</td>
              <td>{{ review.votes_positive_count }}/{{ review.votes_negative_count }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <ul class="pagination">
        {% set pages = count//limit %}
        {% if count%limit %}
          {% set pages = pages+1 %}
        {% endif %}
        {% if pages>1 %}
          {% for p in range(pages) %}
            {% set p_offset = p*limit %}
            <li {% if offset == p_offset %}class="active"{% endif %}>
              <a href="{{ url_for('release_group.entity', id=id, limit=limit, offset=p*limit) }}">{{ p+1 }}</a>
            </li>
          {% endfor %}
        {% endif %}
      </ul>
    {% endif %}

    {% if release and release['medium-list'] %}
      <h4>{{ _('Tracklist') }}</h4>
      <table class="table table-condensed table-hover">
        <thead>
        <tr>
          <th>{{ _('#') }}</th>
          <th>{{ _('Title') }}</th>
          <th>{{ _('Length') }}</th>
        </tr>
        </thead>
        <tbody>
          {% for medium in release['medium-list'] %}
            <tr>
              <td></td>
              <td style="font-size:12px;" colspan="2">
                <b>{{ medium.format | default(_('Medium')) }} {{ medium.position }}</b>
              </td>
            </tr>
            {% for track in medium['track-list'] %}
              <tr>
                <td>{{ track.number }}</td>
                <td>
                  <a href="http://acousticbrainz.org/{{ track.recording.id }}" title="View on AcousticBrainz">
                    {{ track.recording.title }}
                  </a>
                </td>
                <td>
                  {% if track.recording.length %}
                    {{ track.recording.length | track_length }}
                  {% else %}
                    -
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          {% endfor %}
        </tbody>
      </table>
      {% if release_group['release-list']|length > 1 %}
        <em class="text-muted small">
          {{ _('This is a tracklist from one of releases.') }}
          <a href="https://musicbrainz.org/release-group/{{ release_group.id }}">{{ _('See all on MusicBrainz') }}</a>.
        </em>
      {% endif %}
    {% endif %}
  </div>

  <div class="col-md-3">
    <h4>{{ _('Release group information') }}</h4>
    <p>
      {% if release_group['first-release-date'] %}{{ _('First release in %(year)s', year=release_group['first-release-date'][:4]) }}{% endif %}
    </p>
    {% if release_group['external-urls'] %}
      <b>{{ _('External links') }}</b>
      <ul class="list-unstyled external-links">
        {% for url in release_group['external-urls'] %}
          <li class="clearfix">
            <div class="favicon-container">
              {% if url.icon %}
                <img src="{{ url_for('static', filename='favicons/'+url.icon) }}" />
              {% else %}
                <img src="{{ url_for('static', filename='favicons/external-16.png') }}" />
              {% endif %}
            </div>
            <a href="{{ url.target }}">{{ url.name }}</a>
            {% if url.disambiguation %}<span class="text-muted">({{ url.disambiguation }})</span>{% endif %}
          </li>
        {% endfor %}
      </ul>
    {% endif %}

    <div class="external-links">
      <div class="favicon-container"><img src="{{ url_for('static', filename='favicons/musicbrainz-16.ico') }}" /></div>
      <a href="//musicbrainz.org/release-group/{{ release_group.id }}"><em>{{ _('Edit on MusicBrainz') }}</em></a>
    </div>
  </div>
</div>
{% endblock %}