critiquebrainz/frontend/profile/forms.py
from flask_wtf import Form
from flask_babel import gettext
from wtforms import StringField, BooleanField, validators
from wtforms.fields.html5 import EmailField


class ProfileEditForm(Form):
    display_name = StringField(gettext("Display name"), [
        validators.DataRequired(message=gettext("Display name field is empty.")),
        validators.Length(min=3, message=gettext("Display name needs to be at least 3 characters long.")),
        validators.Length(max=64, message=gettext("Display name needs to be at most 64 characters long."))])
    email = EmailField(gettext("Email"), [
        validators.Optional(strip_whitespace=False),
        validators.Email(message=gettext("Email field is not a valid email address."))])
    show_gravatar = BooleanField(gettext("Show my Gravatar"))

critiquebrainz/frontend/__init__.py
from flask import Flask
from flask_debugtoolbar import DebugToolbarExtension


def create_app(debug=None):
    app = Flask(__name__)

    # Configuration files
    import critiquebrainz.default_config
    app.config.from_object(critiquebrainz.default_config)
    app.config.from_pyfile('../config.py', silent=True)
    if debug is not None:
        app.debug = debug

    # Error handling
    import errors
    errors.init_error_handlers(app)

    # Logging
    from critiquebrainz import loggers
    loggers.init_loggers(app)

    if app.debug:
        # Debug toolbar
        DebugToolbarExtension(app)
        app.config['DEBUG_TB_TEMPLATE_EDITOR_ENABLED'] = True

    from flask_uuid import FlaskUUID
    FlaskUUID(app)

    from critiquebrainz.data import db
    db.init_app(app)

    # Memcached
    if 'MEMCACHED_SERVERS' in app.config:
        from critiquebrainz import cache
        cache.init(app.config['MEMCACHED_SERVERS'],
                   app.config['MEMCACHED_NAMESPACE'],
                   debug=1 if app.debug else 0)

    import babel
    babel.init_app(app)

    import login
    login.login_manager.init_app(app)
    from login.provider import MusicBrainzAuthentication
    login.mb_auth = MusicBrainzAuthentication(
        name='musicbrainz',
        client_id=app.config['MUSICBRAINZ_CLIENT_ID'],
        client_secret=app.config['MUSICBRAINZ_CLIENT_SECRET'],
        authorize_url="https://musicbrainz.org/oauth2/authorize",
        access_token_url="https://musicbrainz.org/oauth2/token",
        base_url="https://musicbrainz.org/")

    # APIs
    from apis import mbspotify
    mbspotify.init(app.config['MBSPOTIFY_BASE_URI'], app.config['MBSPOTIFY_ACCESS_KEY'])
    from apis import musicbrainz
    musicbrainz.init(app.config['MUSICBRAINZ_USERAGENT'], critiquebrainz.__version__,
                     hostname=app.config['MUSICBRAINZ_HOSTNAME'])

    # Template utilities
    app.jinja_env.add_extension('jinja2.ext.do')
    from critiquebrainz.utils import reformat_date, reformat_datetime, track_length
    app.jinja_env.filters['date'] = reformat_date
    app.jinja_env.filters['datetime'] = reformat_datetime
    app.jinja_env.filters['track_length'] = track_length
    app.jinja_env.filters['release_group_details'] = musicbrainz.get_release_group_by_id

    # Blueprints
    from views import frontend_bp
    from review.views import review_bp
    from search.views import search_bp
    from artist.views import artist_bp
    from release_group.views import release_group_bp
    from mapping.views import mapping_bp
    from user.views import user_bp
    from profile.views import profile_bp
    from profile.applications.views import profile_apps_bp
    from login.views import login_bp
    from oauth.views import oauth_bp
    from reports.views import reports_bp

    app.register_blueprint(frontend_bp)
    app.register_blueprint(review_bp, url_prefix='/review')
    app.register_blueprint(search_bp, url_prefix='/search')
    app.register_blueprint(artist_bp, url_prefix='/artist')
    app.register_blueprint(release_group_bp, url_prefix='/release-group')
    app.register_blueprint(mapping_bp, url_prefix='/mapping')
    app.register_blueprint(user_bp, url_prefix='/user')
    app.register_blueprint(profile_bp, url_prefix='/profile')
    app.register_blueprint(profile_apps_bp, url_prefix='/profile/applications')
    app.register_blueprint(login_bp, url_prefix='/login')
    app.register_blueprint(oauth_bp, url_prefix='/oauth')
    app.register_blueprint(reports_bp, url_prefix='/reports')

    return app

critiquebrainz/frontend/apis/__init__.py
"""
This package (api) provides modules to access external services:
 - MusicBrainz (with advanced relationship support)
 - Spotify
 - mbspotify

See documentation in each module for information about usage.
"""

critiquebrainz/frontend/artist/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_babel import gettext
from werkzeug.exceptions import BadRequest, NotFound
from critiquebrainz.frontend.apis import musicbrainz
from critiquebrainz.data.model.review import Review

artist_bp = Blueprint('artist', __name__)


@artist_bp.route('/<uuid:id>')
def entity(id):
    """Artist page.

    Displays release groups (split up into several sections depending on their
    type), artist information (type, members/member of, external links).
    """
    artist = musicbrainz.get_artist_by_id(id)
    if not artist:
        raise NotFound(gettext("Sorry, we couldn't find an artist with that MusicBrainz ID."))

    # Preparing artist-rels
    if 'band-members' in artist:
        artist['current_members'] = []
        artist['former_members'] = []
        for member in artist['band-members']:
            if 'ended' in member and member['ended'] == 'true':
                artist['former_members'].append(member)
            else:
                artist['current_members'].append(member)


    release_type = request.args.get('release_type', default='album')
    if release_type not in ['album', 'single', 'ep', 'broadcast', 'other']:  # supported release types
        raise BadRequest("Unsupported release type.")

    page = int(request.args.get('page', default=1))
    if page < 1:
        return redirect(url_for('.reviews'))
    limit = 20
    offset = (page - 1) * limit
    count, release_groups = musicbrainz.browse_release_groups(artist_id=id, release_types=[release_type],
                                                              limit=limit, offset=offset)
    for release_group in release_groups:
        # TODO(roman): Count reviews instead of fetching them.
        reviews, review_count = Review.list(release_group=release_group['id'], sort='created', limit=1)
        release_group['review_count'] = review_count
    return render_template('artist.html', id=id, artist=artist, release_type=release_type,
                           release_groups=release_groups, page=page, limit=limit, count=count)

critiquebrainz/frontend/login/__init__.py
"""
Package login provides authentication functionality for CritiqueBrainz.

It is based on OAuth2 protocol. MusicBrainz is the only supported provider.
"""
from flask import redirect, url_for
from flask_login import LoginManager, current_user
from flask_babel import gettext
from critiquebrainz.data.model.user import User
from werkzeug.exceptions import Unauthorized
from functools import wraps

mb_auth = None

login_manager = LoginManager()
login_manager.login_view = 'login.index'
login_manager.login_message = gettext(u"Please sign in to access this page.")
login_manager.localize_callback = gettext


@login_manager.user_loader
def load_user(user_id):
    return User.get(id=user_id)


def login_forbidden(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if current_user.is_anonymous() is False:
            return redirect(url_for('frontend.index'))
        return f(*args, **kwargs)

    return decorated


def admin_view(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not current_user.is_admin():
            raise Unauthorized(gettext('You must be an administrator to view this page.'))
        return f(*args, **kwargs)

    return decorated

critiquebrainz/frontend/login/views.py
from flask import Blueprint, request, redirect, render_template, url_for, session, flash
from flask_login import login_user, logout_user, login_required
from flask_babel import gettext
from critiquebrainz.frontend.login import mb_auth, login_forbidden

login_bp = Blueprint('login', __name__)


@login_bp.route('/')
@login_forbidden
def index():
    return render_template('login/login.html')


@login_bp.route('/musicbrainz')
@login_forbidden
def musicbrainz():
    session['next'] = request.args.get('next')
    return redirect(mb_auth.get_authentication_uri())


@login_bp.route('/musicbrainz/post')
@login_forbidden
def musicbrainz_post():
    """Callback endpoint."""
    if mb_auth.validate_post_login():
        login_user(mb_auth.get_user())
        next = session.get('next')
        if next:
            return redirect(next)
    else:
        flash(gettext("Login failed."), 'error')
    return redirect(url_for('frontend.index'))


@login_bp.route('/logout')
@login_required
def logout():
    logout_user()
    session.clear()
    return redirect(url_for('frontend.index'))

critiquebrainz/frontend/mapping/__init__.py
"""
Package mapping is basically an interface for mbspotify project.

It allows users to create mappings between release groups and albums on
Spotify. These mappings are then used to show embedded Spotify player on some
pages. See https://github.com/metabrainz/mbspotify for more info about this
project.
"""

critiquebrainz/frontend/mapping/views.py
from flask import Blueprint, render_template, request, url_for, redirect, flash
from flask_login import login_required, current_user
from flask_babel import gettext
from werkzeug.exceptions import NotFound
import critiquebrainz.frontend.apis.spotify as spotify_api
from critiquebrainz.frontend.apis import musicbrainz, mbspotify
from urlparse import urlparse
import os.path
import string

mapping_bp = Blueprint('mapping', __name__)


@mapping_bp.route('/<uuid:release_group_id>')
def spotify_list(release_group_id):
    """This view lists all Spotify albums mapped to a specified release group."""
    spotify_mappings = mbspotify.mappings(str(release_group_id))

    # Converting Spotify URIs to IDs
    spotify_ids = []
    for mapping in spotify_mappings:
        spotify_ids.append(mapping[14:])

    if len(spotify_ids) > 0:
        spotify_albums = spotify_api.get_multiple_albums(spotify_ids)
    else:
        spotify_albums = []
    release_group = musicbrainz.get_release_group_by_id(release_group_id)
    if not release_group:
        raise NotFound("Can't find release group with a specified ID.")
    return render_template('mapping/list.html', spotify_albums=spotify_albums,
                           release_group=release_group)


@mapping_bp.route('/spotify/add')
def spotify():
    release_group_id = request.args.get('release_group_id')
    if not release_group_id:
        return redirect(url_for('frontend.index'))

    release_group = musicbrainz.get_release_group_by_id(release_group_id)
    if not release_group:
        flash(gettext("Only existing release groups can be mapped to Spotify!"), 'error')
        return redirect(url_for('search.index'))

    page = int(request.args.get('page', default=1))
    if page < 1:
        return redirect(url_for('.spotify'))
    limit = 16
    offset = (page - 1) * limit

    # Removing punctuation from the string
    punctuation_map = dict((ord(char), None) for char in string.punctuation)
    query = unicode(release_group['title']).translate(punctuation_map)
    # Searching...
    response = spotify_api.search(query, 'album', limit, offset).get('albums')
    return render_template('mapping/spotify.html', release_group=release_group, search_results=response.get('items'),
                           page=page, limit=limit, count=response.get('total'))


@mapping_bp.route('/spotify/confirm', methods=['GET', 'POST'])
@login_required
def spotify_confirm():
    """Confirmation page for adding new Spotify mapping."""
    release_group_id = request.args.get('release_group_id')
    release_group = musicbrainz.get_release_group_by_id(release_group_id)
    if not release_group:
        flash(gettext("Only existing release groups can be mapped to Spotify!"), 'error')
        return redirect(url_for('search.index'))

    spotify_ref = request.args.get('spotify_ref', default=None)
    if not spotify_ref:
        flash(gettext("You need to select an album from Spotify!"), 'error')
        return redirect(url_for('.spotify', release_group_id=release_group_id))

    spotify_id = parse_spotify_id(spotify_ref)
    if not spotify_id:
        flash(gettext("You need to specify a correct link to this album on Spotify!"), 'error')
        return redirect(url_for('.spotify', release_group_id=release_group_id))

    album = spotify_api.get_album(spotify_id)
    if not album or album.get('error'):
        flash(gettext("You need to specify existing album from Spotify!"), 'error')
        return redirect(url_for('.spotify', release_group_id=release_group_id))

    if request.method == 'POST':
        # TODO(roman): Check values that are returned by add_mapping (also take a look at related JS).
        mbspotify.add_mapping(release_group_id, 'spotify:album:%s' % spotify_id, current_user.id)
        flash(gettext("Spotify mapping has been added!"), 'success')
        return redirect(url_for('.spotify_list', release_group_id=release_group_id))

    return render_template('mapping/confirm.html', release_group=release_group, spotify_album=album)


@mapping_bp.route('/spotify/report', methods=['GET', 'POST'])
@login_required
def spotify_report():
    """Endpoint for reporting incorrect Spotify mappings.

    Shows confirmation page before submitting report to mbspotify.
    """
    release_group_id = request.args.get('release_group_id')
    spotify_id = request.args.get('spotify_id')
    spotify_uri = "spotify:album:" + spotify_id

    # Checking if release group exists
    release_group = musicbrainz.get_release_group_by_id(release_group_id)
    if not release_group:
        flash(gettext("Can't find release group with that ID!"), 'error')
        return redirect(url_for('.spotify_list', release_group_id=release_group_id))

    # Checking if release group is mapped to Spotify
    spotify_mappings = mbspotify.mappings(str(release_group_id))
    if not (spotify_uri in spotify_mappings):
        flash(gettext("This album is not mapped to Spotify yet!"), 'error')
        return redirect(url_for('.spotify_list', release_group_id=release_group_id))

    if request.method == 'POST':
        mbspotify.vote(release_group_id, spotify_uri, current_user.id)
        flash(gettext("Incorrect Spotify mapping has been reported. Thank you!"), 'success')
        return redirect(url_for('.spotify_list', release_group_id=release_group_id))

    else:
        album = spotify_api.get_album(spotify_id)
        if not album or album.get('error'):
            flash(gettext("You need to specify existing album from Spotify!"), 'error')
            return redirect(url_for('.spotify_list', release_group_id=release_group_id))

        return render_template('mapping/report.html', release_group=release_group, spotify_album=album)


def parse_spotify_id(spotify_ref):
    """Extracts Spotify ID out of reference to an album on Spotify.

    Supported reference types:
      - Spotify URI (spotify:album:6IH6co1QUS7uXoyPDv0rIr)
      - HTTP link (http://open.spotify.com/album/6IH6co1QUS7uXoyPDv0rIr)
    """
    # Spotify URI
    if spotify_ref.startswith('spotify:album:'):
        return spotify_ref[14:]

    # Link to Spotify
    # TODO(roman): Improve checking there. See https://bitbucket.org/metabrainz/critiquebrainz/pull-request/167/cb-115-support-for-different-types-of/activity#comment-2757329
    if spotify_ref.startswith('http://') or spotify_ref.startswith('https://'):
        if spotify_ref.endswith('/'):
            spotify_ref = spotify_ref[:-1]
        return os.path.split(urlparse(spotify_ref).path)[-1]

    # TODO(roman): Raise exception if failed to parse!

critiquebrainz/frontend/release_group/views.py
from flask import Blueprint, render_template, request
from flask_login import current_user
from flask_babel import gettext
from critiquebrainz.frontend.apis import musicbrainz, mbspotify
from critiquebrainz.data.model.review import Review
from werkzeug.exceptions import NotFound


release_group_bp = Blueprint('release_group', __name__)


@release_group_bp.route('/<uuid:id>')
def entity(id):
    id = str(id)
    release_group = musicbrainz.get_release_group_by_id(id)
    if not release_group:
        raise NotFound(gettext("Sorry, we couldn't find a release group with that MusicBrainz ID."))
    if len(release_group['release-list']) > 0:
        release = musicbrainz.get_release_by_id(release_group['release-list'][0]['id'])
    else:
        release = None
    spotify_mappings = mbspotify.mappings(id)
    limit = int(request.args.get('limit', default=10))
    offset = int(request.args.get('offset', default=0))
    if current_user.is_authenticated():
        my_reviews, my_count = Review.list(release_group=id, user_id=current_user.id)
        if my_count != 0:
            my_review = my_reviews[0]
        else:
            my_review = None
    else:
        my_review = None
    reviews, count = Review.list(release_group=id, sort='rating', limit=limit, offset=offset)
    return render_template('release_group.html', id=id, release_group=release_group, reviews=reviews,
                           release=release, my_review=my_review, spotify_mappings=spotify_mappings,
                           limit=limit, offset=offset, count=count)

critiquebrainz/frontend/templates/mapping/confirm.html
{% extends 'base.html' %}

{% block title %}{{ _('New Spotify mapping confirmation') }} - CritiqueBrainz{% endblock %}

{% block content %}
<h2>{{ _('Spotify album mapping confirmation') }}</h2>
<div class="text-center">
  <strong style="font-size: 16px">{{ _('Are you sure you want to create a connection?') }}</strong>
  <hr />
  <div class="row">
    <div class="col-md-6">
      <h4>CritiqueBrainz</h4>
      <p>{{ _('%(album)s by %(artist)s', album=release_group.title, artist=release_group['artist-credit-phrase']) }}</p>
      <img id="cover-art">
      <script>
        $("img").last()
            .on("error", function () { $(this).attr("src", "/static/img/missing-art.png"); })
            .attr("src", "//coverartarchive.org/release-group/{{ release_group.id }}/front-250");
      </script>
    </div>
    <div class="col-md-6">
      <h4>{{ _('Spotify') }}</h4>
      <p>{{ _('URI:') }} {{ spotify_album.uri }}</p>
      <iframe src="https://embed.spotify.com/?uri={{ spotify_album.uri }}&theme=white"
              width="250" height="330" frameborder="0" allowtransparency="true"></iframe>
    </div>
  </div>
  <hr />
  <form role="form" method="POST" action="{{ url_for('mapping.spotify_confirm', spotify_ref=spotify_album.uri, release_group_id=release_group.id) }}">
    <button type="submit" class="btn btn-success">{{ _('Connect') }}</button>
    <a href="{{ url_for('release_group.entity', id=release_group.id) }}" class="btn btn-danger">{{ _('Cancel') }}</a>
  </form>
</div>
{% endblock %}

critiquebrainz/frontend/templates/mapping/list.html
{% extends 'base.html' %}

{% block title %}{{ _('Spotify mappings') }} - CritiqueBrainz{% endblock %}

{% block content %}
  <h2>
  {% set artist = [] %}
  {% for credit in release_group['artist-credit'] %}
    {% if credit.artist %}
      {% do artist.append('<a href="%s">'|safe % url_for('artist.entity', id=credit.artist.id) ~ credit.artist.name ~ '</a>'|safe) %}
    {% else %}
      {% do artist.append(credit) %}
    {% endif %}
  {% endfor %}

    {{ _('%(album)s by %(artist)s',
     album = '<a href="%s">%s</a>'|safe % (url_for('release_group.entity', id=release_group.id), release_group.title),
     artist = artist|join()) }}

    {% if release_group['first-release-date'] %}
      <small>{{ release_group['first-release-date'][:4] }}</small>
    {% endif %}
  </h2>

  <h3>{{ _('Spotify mappings') }}</h3>

  {% if not spotify_albums %}
    <p class="lead" style="text-align:center;">{{ _('No mappings') }}</p>
  {% else %}
      <table class="table table-hover">
        <thead>
        <tr>
          <th>{# Cover art #}</th>
          <th>{{ _('Type') }}</th>
          <th>{{ _('ID') }}</th>
          <th>{{ _('Album') }}</th>
          <th>{{ _('Artist') }}</th>
          <th>{{ _('Release date') }}</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        {% for mbid, album in spotify_albums.iteritems() %}
          <tr>
            <td>
              <img src="{{ album.images[-1].url if album.images else '/static/img/missing-art.png' }}"
                   style="max-height: 25px;" />
            </td>
            <td>{{ album.type }}</td>
            <td><a href="{{ album.external_urls.spotify }}">{{ album.id }}</a></td>
            <td>{{ album.name }}</td>
            <td>
              {# Generating a list of artists #}
              {% set artists = [] %}
              {% for artist in album.artists %}
                {% do artists.append(artist.name) %}
              {% endfor %}
              {{ artists|join(', ') }}
            </td>
            <td>{{ album.release_date }}</td>
            <td><a class="btn btn-danger btn-xs" href="{{ url_for('mapping.spotify_report', release_group_id=release_group.id, spotify_id=album.id) }}">{{ _('Incorrect') }}</a></td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
  {% endif %}
  <b><a class="btn btn-primary btn-default" href="{{ url_for('mapping.spotify', release_group_id=release_group.id) }}">{{ _('+ Add new mapping') }}</a></b>
{% endblock %}

critiquebrainz/frontend/templates/mapping/report.html
{% extends 'base.html' %}

{% block title %}{{ _('Incorrect mapping reporting') }} - CritiqueBrainz{% endblock %}

{% block content %}
<h2>{{ _('Incorrect mapping reporting') }}</h2>
<div class="text-center">
  <strong style="font-size: 16px">{{ _('Are you sure you want to report incorrect mapping?') }}</strong>
  <hr />
  <div class="row">
    <div class="col-md-6">
      <h4>CritiqueBrainz</h4>
      <p>{{ _('%(album)s by %(artist)s', album=release_group.title, artist=release_group['artist-credit-phrase']) }}</p>
      <img id="cover-art">
      <script>
        $("img").last()
            .on("error", function () { $(this).attr("src", "/static/img/missing-art.png"); })
            .attr("src", "//coverartarchive.org/release-group/{{ release_group.id }}/front-250");
      </script>
    </div>
    <div class="col-md-6">
      <h4>{{ _('Spotify') }}</h4>
      <p>{{ _('URI:') }} {{ spotify_album.uri }}</p>
      <iframe src="https://embed.spotify.com/?uri={{ spotify_album.uri }}&theme=white"
              width="250" height="330" frameborder="0" allowtransparency="true"></iframe>
    </div>
  </div>
  <hr />
  <form role="form" method="POST" action="{{ url_for('mapping.spotify_report', release_group_id=release_group.id, spotify_id=spotify_album.id) }}">
    <button type="submit" class="btn btn-danger">{{ _('Report incorrect mapping') }}</button>
    <a href="{{ url_for('mapping.spotify_list', release_group_id=release_group.id) }}" class="btn btn-default">{{ _('Cancel') }}</a>
  </form>
</div>
{% endblock %}

critiquebrainz/frontend/templates/mapping/spotify.html
{% extends 'base.html' %}

{% block title %}{{ _('Spotify album mapping') }} - CritiqueBrainz{% endblock %}

{% block content %}
<h2>{{ _('Spotify album mapping') }}</h2>
<p class="lead">
  {% if release_group['first-release-date'] %}
    {% set album = '"%s" <span class="text-muted">(%s)</span>'|safe % (release_group.title, release_group['first-release-date'][:4]) %}
  {% else %}
    {% set album = '"%s"' % release_group.title %}
  {% endif %}

  {{ _('Please select the album %(album)s by %(artist)s, or provide a link to Spotify below.',
       album=album, artist=release_group['artist-credit-phrase']) }}
</p>
{% if search_results %}
  <div id="spotify-search-results" class="row">
    {% for item in search_results %}
    <div class="col-md-3">
      <div class="thumbnail">
        <div class="cover-art-container">
          <a href="{{ url_for('mapping.spotify_confirm', release_group_id=release_group.id, spotify_ref=item.uri) }}" class="match-link" data-toggle="tooltip" data-placement="bottom" title="This is the same album!" rel="nofollow">
            {% if item.images %}
              <img class="img-responsive" src="{{ item.images[0].url }}" />
            {% else %}
              <img class="img-responsive" src="/static/img/missing-art.png" />
            {% endif %}
          </a>
        </div>
        <div class="caption">
          <div class="title">{{ item.name }}</div>
          <span class="text-muted">{{ item.album_type }}</span><br />
          <em><a href="{{ item.external_urls.spotify }}">{{ _('Listen on Spotify') }}</a></em><br />
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% if count > limit %}
    <div class="row">
      <div class="col-md-12">
        <ul class="pager">
          {% if page > 1 %}
            <li class="previous"><a href="{{ url_for('mapping.spotify', release_group_id=release_group.id, page=page-1) }}">&larr; {{ _('Previous') }}</a></li>
          {% endif %}
          {% if page-1 < count//limit %}
            <li class="next"><a href="{{ url_for('mapping.spotify', release_group_id=release_group.id, page=page+1) }}">{{ _('Next') }} &rarr;</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  {% endif %}
{% else %}
  <p class="lead" style="text-align:center; margin-top:20px;">{{ _('No similar albums found') }}</p>
{% endif %}

<hr />

<p>
  <p>{{ _('If you can\'t find the right album in search results, you can paste a Spotify link there:') }}</p>
  <form class="form-inline" role="form" action="{{ url_for('mapping.spotify_confirm', release_group_id=release_group.id) }}" method="GET">
    <div class="form-group">
      <input type="text" class="form-control input-sm" name="spotify_ref" placeholder="{{ _('Spotify URI or HTTP link') }}" size="40">
    </div>
    <button type="submit" class="btn btn-default btn-sm">{{ _('Submit') }}</button>
  </form>
  <br /><small class="text-muted">
    {{ _('A Spotify link should look like %(uri_example)s or %(link_example)s.',
         uri_example = '<code>spotify:album:3CCO9PhQXCQXUWjcEfys9B</code>' | safe,
         link_example = '<code>https://play.spotify.com/album/3CCO9PhQXCQXUWjcEfys9B</code>' | safe) }}
  </small>
</p>

<hr />

<p>
  <strong>
    {{ _('It\'s fine if you can\'t find the right album. It might not be available on Spotify yet.') }}
    {{ _('You can <a href="%(link)s">go back to the release group page</a>.', link=url_for('release_group.entity', id=release_group.id)) }}
  </strong>
</p>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>$('.match-link').tooltip()</script>
{% endblock %}